# Generated by Django 5.1.15 on 2026-09-03 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0012_cyclonedx_schema_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceThreatTaxonomyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_taxonomy_links', to='threats.componentinstancethreat')),
                ('flow_threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_taxonomy_links', to='threats.dataflowinstancethreat')),
                ('taxonomy_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_threat_links', to='threats.taxonomyentry')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('component_threat__isnull', False), ('flow_threat__isnull', True)), models.Q(('component_threat__isnull', True), ('flow_threat__isnull', False)), _connector='OR'), name='taxonomy_link_exactly_one_fk'), models.UniqueConstraint(condition=models.Q(('component_threat__isnull', False)), fields=('taxonomy_entry', 'component_threat'), name='unique_taxonomy_component_threat'), models.UniqueConstraint(condition=models.Q(('flow_threat__isnull', False)), fields=('taxonomy_entry', 'flow_threat'), name='unique_taxonomy_flow_threat')],
            },
        ),
    ]
