# Generated by Django 5.1.15 on 2026-09-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0013_instance_threat_taxonomy_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentinstancethreat',
            name='dismissal_reason',
        ),
        migrations.RemoveField(
            model_name='componentinstancethreat',
            name='is_dismissed',
        ),
        migrations.RemoveField(
            model_name='countermeasurelibrary',
            name='control_type',
        ),
        migrations.RemoveField(
            model_name='dataflowinstancethreat',
            name='dismissal_reason',
        ),
        migrations.RemoveField(
            model_name='dataflowinstancethreat',
            name='is_dismissed',
        ),
        migrations.RemoveField(
            model_name='instancecountermeasure',
            name='control_type',
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='decision_rationale',
            field=models.TextField(blank=True, default='', help_text='Rationale for triage decision (recommended for accept/delegate/eliminate)'),
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='triage_status',
            field=models.CharField(choices=[('open', 'Open'), ('accept', 'Accept'), ('mitigate', 'Mitigate'), ('delegate', 'Delegate'), ('eliminate', 'Eliminate')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='countermeasurelibrary',
            name='control_functions',
            field=models.JSONField(blank=True, default=list, help_text="List of control functions, e.g. ['preventive', 'detective']"),
        ),
        migrations.AddField(
            model_name='countermeasurelibrary',
            name='control_nature',
            field=models.CharField(blank=True, default='', help_text='Control nature: technical, administrative, or physical', max_length=20),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='decision_rationale',
            field=models.TextField(blank=True, default='', help_text='Rationale for triage decision (recommended for accept/delegate/eliminate)'),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='triage_status',
            field=models.CharField(choices=[('open', 'Open'), ('accept', 'Accept'), ('mitigate', 'Mitigate'), ('delegate', 'Delegate'), ('eliminate', 'Eliminate')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='instancecountermeasure',
            name='control_functions',
            field=models.JSONField(blank=True, default=list, help_text='Copied from CountermeasureLibrary.control_functions on creation'),
        ),
        migrations.AddField(
            model_name='instancecountermeasure',
            name='control_nature',
            field=models.CharField(blank=True, default='', help_text='Copied from CountermeasureLibrary.control_nature on creation', max_length=20),
        ),
    ]
